// OP-2: helper that turns a local raster product image URL into the
// sibling .webp generated by scripts/convert-images-to-webp.cjs.
//
// Only swaps URLs that:
//   - point at a local /products/, /case-studies/, or /industries/ path
//   - end in .jpg / .jpeg / .png
//
// Anything else (Shopify CDN, Supabase storage, blob: previews, data:
// URIs, .svg, already-.webp) is returned unchanged so callers can pass
// the result straight to <source srcSet>.

const RASTER_RE = /\.(jpe?g|png)(\?.*)?$/i;
const LOCAL_RE = /^\/(products|case-studies|industries)\//;

export function toWebp(url: string | undefined | null): string {
  if (!url) return '';
  if (!LOCAL_RE.test(url)) return url;
  if (!RASTER_RE.test(url)) return url;
  return url.replace(RASTER_RE, (_m, _ext, query = '') => `.webp${query ?? ''}`);
}
