// Edge function: admin-invite-vendor
// Called by /admin/vendors invite modal.
// Verifies caller is admin/president, generates invite token, persists row,
// and emails the invitation. Replace inline email with Resend integration
// when RESEND_API_KEY is configured.

import { createClient } from 'jsr:@supabase/supabase-js@2';

interface InviteBody {
  email: string;
  full_name: string;
  role?: 'admin' | 'vendor';
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return json({ error: 'Missing auth' }, 401);
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

    // Caller-scoped client to verify role
    const callerClient = createClient(supabaseUrl, Deno.env.get('SUPABASE_ANON_KEY')!, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: { user } } = await callerClient.auth.getUser();
    if (!user) return json({ error: 'Not authenticated' }, 401);

    const { data: profile } = await callerClient
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .maybeSingle();
    if (!profile || (profile.role !== 'admin' && profile.role !== 'president')) {
      return json({ error: 'Forbidden — admin role required' }, 403);
    }

    const body: InviteBody = await req.json();
    if (!body.email || !body.full_name) {
      return json({ error: 'email and full_name required' }, 400);
    }
    const role = body.role === 'admin' ? 'admin' : 'vendor';

    const adminClient = createClient(supabaseUrl, serviceKey);

    // Persist invite row (token auto-generated by DB default)
    const { data: invite, error: insertErr } = await adminClient
      .from('vendor_invites')
      .insert({
        email: body.email.toLowerCase().trim(),
        full_name: body.full_name.trim(),
        role,
        invited_by: user.id,
      })
      .select('token, email, full_name, role, expires_at')
      .single();
    if (insertErr || !invite) {
      return json({ error: insertErr?.message ?? 'Insert failed' }, 500);
    }

    // Send via Supabase Auth admin invite (sends magic link automatically)
    const siteUrl = Deno.env.get('SITE_URL') ?? 'https://visionaffichage.com';
    const { error: inviteErr } = await adminClient.auth.admin.inviteUserByEmail(invite.email, {
      data: { full_name: invite.full_name, intended_role: role, invite_token: invite.token },
      redirectTo: `${siteUrl}/admin/accept-invite/${invite.token}`,
    });
    if (inviteErr) {
      // Email failed but row exists — return token so admin can copy a manual link
      return json({
        ok: true,
        warning: `Email send failed: ${inviteErr.message}. Send this link manually: ${siteUrl}/admin/accept-invite/${invite.token}`,
        invite,
      });
    }

    return json({ ok: true, invite });
  } catch (err) {
    return json({ error: (err as Error).message }, 500);
  }
});

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}
