import { ImgHTMLAttributes } from "react";

/**
 * ProductImage — wraps an <img> in a <picture> element that prefers a
 * sibling .webp asset (generated by scripts/convert-images-to-webp.cjs)
 * and falls back to the original .jpg / .jpeg / .png for browsers that
 * lack WebP support (~3% of traffic in 2025).
 *
 * If the src is not a local raster path under /products/, /case-studies/
 * or /industries/, it renders a plain <img> without the WebP swap.
 */
export interface ProductImageProps extends ImgHTMLAttributes<HTMLImageElement> {
  src: string;
  alt: string;
}

const RASTER_RE = /\.(jpe?g|png)$/i;
const LOCAL_RE = /^\/(products|case-studies|industries)\//;

export function ProductImage({ src, alt, ...rest }: ProductImageProps) {
  const isSwappable =
    typeof src === "string" && LOCAL_RE.test(src) && RASTER_RE.test(src);

  if (!isSwappable) {
    return <img src={src} alt={alt} {...rest} />;
  }

  const webpSrc = src.replace(RASTER_RE, ".webp");
  return (
    <picture>
      <source srcSet={webpSrc} type="image/webp" />
      <img src={src} alt={alt} {...rest} />
    </picture>
  );
}

export default ProductImage;
